feat: #609 aip exchange keys
ucfyao/moow-api-express pull request #43
Opened 2024-06-06 15:48 UTC by wjtwzgl12

2024-06-06 19:38 UTC, linj121 commented on app/keys/damoon.pem
😱😱😱 Dangerous

2024-06-07 07:26 UTC, Wongcheukwai commented on app/keys/damoon.pem
please be more specific about the comment since the emojis and the word "dangerous" seem like a serious matter.

2024-06-07 08:05 UTC, Wongcheukwai reviewed
Hi Ryan, 
Thank you for submitting your PR. Nice work. I have some suggestions: 

1. in the services folder, please capitalise the letter E to align with other places.
2. Could you please add "update function" as I can see this function in  the old version.
3. Could you explain what's aip stands for as I think its seems nebulous to most contributors.

Regards
Kelsey

2024-06-07 08:07 UTC, Wongcheukwai requested changes
Hi Ryan,
Thank you for submitting your PR. Nice work. I have some suggestions:

    in the services folder, please capitalise the letter E to align with other places.
    Could you please add "update function" as I can see this function in the old version.
    Could you explain what's aip stands for as I think its seems nebulous to most contributors.

Regards
Kelsey

2024-06-08 00:44 UTC, linj121 commented on app/keys/damoon.pem
Uploading private key to a public repository can lead to security issues

2024-06-08 05:49 UTC, closed without merging